version: '3.3'

services:
  
  web:
    image: dockersamples/aspnet-monitoring-website:${BUILD_NUMBER:-latest}
    ports:
    - "80:80"
    networks:
      - app-net    

  prometheus:
    image: dockersamples/aspnet-monitoring-prometheus:${BUILD_NUMBER:-latest}
    ports:
    - "9090:9090"
    networks:
      - app-net 

networks:
  app-net:
    external:
      name: nat